title: My new adventure
author: DruSpace
email: andrewsw88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a website I'm making as I follow along with the tutorial on <i><b>Pages</b></i>.
  Nothing fancy....
   
# site theme
theme: minima

# social links
twitter_username: AndrewWeit # DO NOT include the @ character, or else the build will fail!
github_username:  DruSpace # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
